import { Category, Product } from '@/types'

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Siti Web',
    slug: 'siti-web',
    description: 'Landing page, e-commerce, portfolio e siti aziendali professionali',
    icon: '🌐',
    color: '#6366f1',
    product_count: 8,
  },
  {
    id: '2',
    name: 'Menu Digitali',
    slug: 'menu-digitali',
    description: 'Menu per ristoranti con allergenici, QR code e aggiornamenti inclusi',
    icon: '🍽️',
    color: '#f59e0b',
    product_count: 5,
  },
  {
    id: '3',
    name: 'Fogli Excel',
    slug: 'fogli-excel',
    description: 'Inventari, contabilità, gestione magazzino e fatturazione automatizzata',
    icon: '📊',
    color: '#10b981',
    product_count: 6,
  },
  {
    id: '4',
    name: 'Automazioni',
    slug: 'automazioni',
    description: 'Chatbot, integrazioni API e workflow completamente automatici',
    icon: '🤖',
    color: '#8b5cf6',
    product_count: 4,
  },
  {
    id: '5',
    name: 'App Mobile',
    slug: 'app-mobile',
    description: 'PWA installabili, app iOS e Android su misura per il tuo business',
    icon: '📱',
    color: '#ec4899',
    product_count: 3,
  },
]

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Landing Page Pro',
    slug: 'landing-page-pro',
    description: 'Landing page ad alta conversione con design moderno e SEO ottimizzato',
    long_description: 'Una landing page professionale progettata per convertire i visitatori in clienti. Include sezioni hero, servizi, testimonianze, CTA e form di contatto. Ottimizzata per tutti i dispositivi e per i motori di ricerca.',
    price: 199,
    original_price: 349,
    category_id: '1',
    delivery_time: '24-48 ore',
    is_customizable: true,
    is_bestseller: true,
    is_digital: true,
    badge: 'bestseller',
    includes: [
      'Design responsive (mobile + desktop)',
      'SEO on-page ottimizzato',
      'Form di contatto funzionante',
      'Google Analytics integrato',
      'Hosting su Vercel incluso 1 anno',
      'File sorgente consegnato',
    ],
    images: ['/placeholder-site.jpg'],
    rating: 4.9,
    review_count: 47,
    created_at: '2024-01-01',
  },
  {
    id: '2',
    name: 'E-commerce Completo',
    slug: 'ecommerce-completo',
    description: 'Negozio online completo con gestione prodotti, pagamenti e ordini',
    long_description: 'Soluzione e-commerce completa con carrello, pagamenti Stripe/PayPal, gestione inventario, email automatiche e pannello admin. Pronto per vendere in 48 ore.',
    price: 599,
    category_id: '1',
    delivery_time: '3-5 giorni',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: [
      'Catalogo prodotti illimitato',
      'Pagamenti Stripe + PayPal',
      'Pannello admin completo',
      'Email automatiche ordini',
      'Gestione spedizioni',
      'Ottimizzazione SEO',
    ],
    images: [],
    rating: 4.8,
    review_count: 23,
    created_at: '2024-01-01',
  },
  {
    id: '3',
    name: 'Menu Digitale QR',
    slug: 'menu-digitale-qr',
    description: 'Menu digitale per ristoranti con QR code, allergenici e aggiornamenti illimitati',
    long_description: 'Il menu digitale perfetto per il tuo ristorante. Accessibile via QR code, con indicatori allergenici conformi alle normative EU, prezzi aggiornabili in tempo reale, immagini dei piatti e sezioni personalizzabili.',
    price: 149,
    original_price: 249,
    category_id: '2',
    delivery_time: '24 ore',
    is_customizable: true,
    is_bestseller: true,
    is_digital: true,
    badge: '24h',
    includes: [
      'QR code personalizzato',
      'Allergenici EU conformi',
      'Aggiornamenti illimitati',
      'Multilingua (IT, EN)',
      'Dashboard gestione',
      '1 anno hosting incluso',
    ],
    images: [],
    rating: 5.0,
    review_count: 89,
    created_at: '2024-01-01',
  },
  {
    id: '4',
    name: 'Gestionale Inventario Excel',
    slug: 'gestionale-inventario-excel',
    description: 'Foglio Excel professionale per gestione inventario e magazzino',
    long_description: 'Template Excel avanzato per gestire il tuo magazzino in modo professionale. Include tracciamento scorte, alert automatici, report grafici, gestione fornitori e storico movimenti.',
    price: 49,
    category_id: '3',
    delivery_time: '1 ora',
    is_customizable: false,
    is_bestseller: false,
    is_digital: true,
    badge: '24h',
    includes: [
      'Dashboard scorte in tempo reale',
      'Alert livello minimo automatico',
      'Report mensili/annuali',
      'Gestione 10+ fornitori',
      'Storico movimenti 5 anni',
      'Istruzioni video incluse',
    ],
    images: [],
    rating: 4.7,
    review_count: 134,
    created_at: '2024-01-01',
  },
  {
    id: '5',
    name: 'Chatbot WhatsApp Business',
    slug: 'chatbot-whatsapp',
    description: 'Chatbot automatico per WhatsApp Business con risposte AI personalizzate',
    long_description: 'Automatizza il tuo supporto clienti con un chatbot intelligente per WhatsApp Business. Risponde alle domande frequenti, prende prenotazioni, invia cataloghi e integra il tuo CRM.',
    price: 299,
    original_price: 499,
    category_id: '4',
    delivery_time: '2-3 giorni',
    is_customizable: true,
    is_bestseller: true,
    is_digital: true,
    badge: 'bestseller',
    includes: [
      'Setup WhatsApp Business API',
      'Risposte AI personalizzate',
      'Gestione prenotazioni',
      'Integrazione CRM base',
      'Dashboard analytics',
      '3 mesi supporto incluso',
    ],
    images: [],
    rating: 4.9,
    review_count: 31,
    created_at: '2024-01-01',
  },
  {
    id: '6',
    name: 'App PWA Business',
    slug: 'app-pwa-business',
    description: 'Progressive Web App installabile su iOS e Android per il tuo business',
    long_description: 'Una PWA professionale che funziona come una vera app su qualsiasi dispositivo. Installabile dalla home, funziona offline, push notification e performance ottimizzate.',
    price: 449,
    category_id: '5',
    delivery_time: '5-7 giorni',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: [
      'Installabile iOS + Android',
      'Funzionamento offline',
      'Push notification',
      'Performance 95+ Lighthouse',
      'Backend API incluso',
      '6 mesi supporto',
    ],
    images: [],
    rating: 4.8,
    review_count: 12,
    created_at: '2024-01-01',
  },
]
