import { Category, Product } from '@/types'

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Siti Web',
    slug: 'siti-web',
    description: 'Landing page, e-commerce, portfolio e siti aziendali professionali',
    icon: '🌐',
    color: '#6366f1',
    product_count: 4,
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=600&q=80',
  },
  {
    id: '2',
    name: 'Menu Digitali',
    slug: 'menu-digitali',
    description: 'Menu per ristoranti con allergenici, QR code e aggiornamenti inclusi',
    icon: '🍽️',
    color: '#f59e0b',
    product_count: 2,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
  },
  {
    id: '3',
    name: 'Fogli Excel',
    slug: 'fogli-excel',
    description: 'Inventari, contabilità, gestione magazzino e fatturazione automatizzata',
    icon: '📊',
    color: '#10b981',
    product_count: 3,
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&q=80',
  },
  {
    id: '4',
    name: 'Automazioni',
    slug: 'automazioni',
    description: 'Chatbot, integrazioni API e workflow completamente automatici',
    icon: '🤖',
    color: '#8b5cf6',
    product_count: 2,
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80',
  },
  {
    id: '5',
    name: 'App Mobile',
    slug: 'app-mobile',
    description: 'PWA installabili, app iOS e Android su misura per il tuo business',
    icon: '📱',
    color: '#ec4899',
    product_count: 2,
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80',
  },
]

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Landing Page Pro',
    slug: 'landing-page-pro',
    description: 'Landing page ad alta conversione con design moderno e SEO ottimizzato',
    long_description: 'Una landing page professionale progettata per convertire i visitatori in clienti. Include sezioni hero, servizi, testimonianze, CTA e form di contatto. Ottimizzata per tutti i dispositivi e per i motori di ricerca.',
    price: 29,
    original_price: 59,
    category_id: '1',
    delivery_time: '24-48 ore',
    is_customizable: true,
    is_bestseller: true,
    is_digital: true,
    badge: 'bestseller',
    includes: [
      'Design responsive (mobile + desktop)',
      'SEO on-page ottimizzato',
      'Form di contatto funzionante',
      'Google Analytics integrato',
      'File sorgente consegnato',
    ],
    images: ['https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80'],
    rating: 4.9,
    review_count: 47,
    created_at: '2024-01-01',
  },
  {
    id: '2',
    name: 'Sito Aziendale',
    slug: 'sito-aziendale',
    description: 'Sito web completo per la tua azienda con più pagine e CMS',
    long_description: 'Sito aziendale professionale con homepage, chi siamo, servizi, blog e contatti. Pannello CMS per modificare i contenuti autonomamente senza toccare codice.',
    price: 39,
    original_price: 79,
    category_id: '1',
    delivery_time: '3-5 giorni',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: [
      'Fino a 5 pagine personalizzate',
      'CMS per modificare contenuti',
      'Blog integrato',
      'SEO ottimizzato',
      'Hosting Vercel 1 anno',
    ],
    images: ['https://images.unsplash.com/photo-1547658719-da2b51169166?w=800&q=80'],
    rating: 4.8,
    review_count: 23,
    created_at: '2024-01-01',
  },
  {
    id: '3',
    name: 'Menu Digitale QR',
    slug: 'menu-digitale-qr',
    description: 'Menu digitale per ristoranti con QR code, allergenici e aggiornamenti illimitati',
    long_description: 'Il menu digitale perfetto per il tuo ristorante. Accessibile via QR code, con indicatori allergenici conformi alle normative EU, prezzi aggiornabili in tempo reale, immagini dei piatti e sezioni personalizzabili.',
    price: 19,
    original_price: 39,
    category_id: '2',
    delivery_time: '24 ore',
    is_customizable: true,
    is_bestseller: true,
    is_digital: true,
    badge: '24h',
    includes: [
      'QR code personalizzato',
      'Allergenici EU conformi',
      'Aggiornamenti illimitati',
      'Multilingua (IT, EN)',
      '1 anno hosting incluso',
    ],
    images: ['https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80'],
    rating: 5.0,
    review_count: 89,
    created_at: '2024-01-01',
  },
  {
    id: '4',
    name: 'Menu Bar & Cocktail',
    slug: 'menu-bar-cocktail',
    description: 'Menu digitale elegante per bar, pub e cocktail bar con QR code',
    long_description: 'Menu digitale studiato per bar e locali notturni. Design elegante e scuro, sezioni cocktail, spirits, birre e soft drink. QR code personalizzato con il logo del tuo locale.',
    price: 15,
    original_price: 29,
    category_id: '2',
    delivery_time: '24 ore',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: '24h',
    includes: [
      'Design elegante dark mode',
      'QR code con logo',
      'Sezioni cocktail e spirits',
      'Aggiornamenti inclusi 1 anno',
    ],
    images: ['https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80'],
    rating: 4.8,
    review_count: 34,
    created_at: '2024-01-01',
  },
  {
    id: '5',
    name: 'Gestionale Inventario Excel',
    slug: 'gestionale-inventario-excel',
    description: 'Foglio Excel professionale per gestione inventario e magazzino',
    long_description: 'Template Excel avanzato per gestire il tuo magazzino in modo professionale. Include tracciamento scorte, alert automatici, report grafici, gestione fornitori e storico movimenti.',
    price: 10,
    original_price: 19,
    category_id: '3',
    delivery_time: '1 ora',
    is_customizable: false,
    is_bestseller: true,
    is_digital: true,
    badge: '24h',
    includes: [
      'Dashboard scorte in tempo reale',
      'Alert livello minimo automatico',
      'Report mensili grafici',
      'Gestione fornitori',
      'Istruzioni incluse',
    ],
    images: ['https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80'],
    rating: 4.7,
    review_count: 134,
    created_at: '2024-01-01',
  },
  {
    id: '6',
    name: 'Fatturazione Automatica Excel',
    slug: 'fatturazione-automatica-excel',
    description: 'Template Excel per generare fatture professionali in automatico',
    long_description: 'Genera fatture professionali in pochi secondi. Inserisci i dati cliente e i servizi, il foglio calcola tutto automaticamente: IVA, totali, numerazione progressiva e archivio clienti.',
    price: 12,
    original_price: 24,
    category_id: '3',
    delivery_time: '1 ora',
    is_customizable: false,
    is_bestseller: false,
    is_digital: true,
    badge: '24h',
    includes: [
      'Generazione fatture automatica',
      'Calcolo IVA automatico',
      'Archivio clienti',
      'Numerazione progressiva',
      'Export PDF integrato',
    ],
    images: ['https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80'],
    rating: 4.8,
    review_count: 67,
    created_at: '2024-01-01',
  },
  {
    id: '7',
    name: 'Chatbot WhatsApp Business',
    slug: 'chatbot-whatsapp',
    description: 'Chatbot automatico per WhatsApp Business con risposte personalizzate',
    long_description: 'Automatizza il tuo supporto clienti con un chatbot intelligente per WhatsApp Business. Risponde alle domande frequenti, prende prenotazioni e invia informazioni automaticamente.',
    price: 35,
    original_price: 69,
    category_id: '4',
    delivery_time: '2-3 giorni',
    is_customizable: true,
    is_bestseller: true,
    is_digital: true,
    badge: 'bestseller',
    includes: [
      'Setup WhatsApp Business API',
      'Risposte automatiche personalizzate',
      'Gestione prenotazioni',
      'Dashboard analytics',
      '1 mese supporto incluso',
    ],
    images: ['https://images.unsplash.com/photo-1611262588024-d12430b98920?w=800&q=80'],
    rating: 4.9,
    review_count: 31,
    created_at: '2024-01-01',
  },
  {
    id: '8',
    name: 'Automazione Email Marketing',
    slug: 'automazione-email',
    description: 'Workflow automatico per email marketing e follow-up clienti',
    long_description: 'Crea sequenze email automatiche per acquisire e fidelizzare clienti. Setup completo con welcome email, follow-up post acquisto, recupero carrelli abbandonati e newsletter automatiche.',
    price: 25,
    original_price: 49,
    category_id: '4',
    delivery_time: '2-3 giorni',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: [
      'Sequenza welcome email',
      'Follow-up post acquisto',
      'Newsletter automatica mensile',
      'Template email brandizzati',
      'Report aperture e click',
    ],
    images: ['https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800&q=80'],
    rating: 4.7,
    review_count: 19,
    created_at: '2024-01-01',
  },
  {
    id: '9',
    name: 'App PWA Business',
    slug: 'app-pwa-business',
    description: 'Progressive Web App installabile su iOS e Android per il tuo business',
    long_description: 'Una PWA professionale che funziona come una vera app su qualsiasi dispositivo. Installabile dalla home, funziona offline, push notification e performance ottimizzate.',
    price: 40,
    original_price: 79,
    category_id: '5',
    delivery_time: '5-7 giorni',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: [
      'Installabile iOS + Android',
      'Funzionamento offline',
      'Push notification',
      'Performance ottimizzate',
      '3 mesi supporto',
    ],
    images: ['https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80'],
    rating: 4.8,
    review_count: 12,
    created_at: '2024-01-01',
  },
  {
    id: '10',
    name: 'App Prenotazioni',
    slug: 'app-prenotazioni',
    description: 'App mobile per gestire prenotazioni e appuntamenti del tuo locale',
    long_description: 'App PWA per gestire prenotazioni in modo professionale. I clienti prenotano online, ricevono conferma automatica e reminder. Tu gestisci tutto da una dashboard intuitiva.',
    price: 35,
    original_price: 69,
    category_id: '5',
    delivery_time: '5-7 giorni',
    is_customizable: true,
    is_bestseller: true,
    is_digital: true,
    badge: 'bestseller',
    includes: [
      'Booking online clienti',
      'Conferme automatiche',
      'Reminder SMS/email',
      'Dashboard gestione',
      'Calendario integrato',
    ],
    images: ['https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80'],
    rating: 4.9,
    review_count: 28,
    created_at: '2024-01-01',
  },
]
