import { Category, Product } from '@/types'

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Siti Web',
    slug: 'siti-web',
    description: 'Landing page, e-commerce, portfolio e siti aziendali professionali',
    icon: '🌐',
    color: '#6366f1',
    product_count: 7,
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=600&q=80',
  },
  {
    id: '2',
    name: 'Menu Digitali',
    slug: 'menu-digitali',
    description: 'Menu per ristoranti con allergenici, QR code e aggiornamenti inclusi',
    icon: '🍽️',
    color: '#f59e0b',
    product_count: 6,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
  },
  {
    id: '3',
    name: 'Fogli Excel',
    slug: 'fogli-excel',
    description: 'Inventari, contabilità, gestione magazzino e fatturazione automatizzata',
    icon: '📊',
    color: '#10b981',
    product_count: 7,
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&q=80',
  },
  {
    id: '4',
    name: 'Automazioni',
    slug: 'automazioni',
    description: 'Chatbot, integrazioni API e workflow completamente automatici',
    icon: '🤖',
    color: '#8b5cf6',
    product_count: 6,
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80',
  },
  {
    id: '5',
    name: 'App Mobile',
    slug: 'app-mobile',
    description: 'PWA installabili, app iOS e Android su misura per il tuo business',
    icon: '📱',
    color: '#ec4899',
    product_count: 3,
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80',
  },
]

export const PRODUCTS: Product[] = [

  // ─── SITI WEB ───
  {
    id: '1',
    name: 'Landing Page Pro',
    slug: 'landing-page-pro',
    description: 'Landing page ad alta conversione con design moderno e SEO ottimizzato',
    long_description: 'Una landing page professionale progettata per convertire i visitatori in clienti. Include sezioni hero, servizi, testimonianze, CTA e form di contatto. Ottimizzata per tutti i dispositivi e per i motori di ricerca.',
    price: 29,
    original_price: 59,
    category_id: '1',
    delivery_time: '24-48 ore',
    is_customizable: true,
    is_bestseller: true,
    is_digital: true,
    badge: 'bestseller',
    includes: ['Design responsive mobile + desktop', 'SEO on-page ottimizzato', 'Form di contatto funzionante', 'Google Analytics integrato', 'File sorgente consegnato'],
    images: ['https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80'],
    rating: 4.9, review_count: 47, created_at: '2024-01-01',
  },
  {
    id: '2',
    name: 'Sito Portfolio Creativo',
    slug: 'sito-portfolio-creativo',
    description: 'Portfolio online elegante per freelancer, designer, fotografi e creativi',
    long_description: 'Un portfolio online che ti fa distinguere dalla concorrenza. Design minimal ed elegante, galleria progetti con lightbox, sezione about, contatti e integrazione social. Perfetto per fotografi, designer e freelancer.',
    price: 25,
    original_price: 49,
    category_id: '1',
    delivery_time: '24-48 ore',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: ['Galleria progetti con lightbox', 'Sezione about e bio', 'Form contatto', 'Integrazione social media', 'Design minimal premium'],
    images: ['https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80'],
    rating: 4.8, review_count: 31, created_at: '2024-01-01',
  },
  {
    id: '3',
    name: 'Sito Aziendale 5 Pagine',
    slug: 'sito-aziendale',
    description: 'Sito web completo per la tua azienda con più pagine e CMS integrato',
    long_description: 'Sito aziendale professionale con homepage, chi siamo, servizi, blog e contatti. Pannello CMS per modificare i contenuti autonomamente senza toccare codice. Ottimizzato SEO e veloce.',
    price: 39,
    original_price: 79,
    category_id: '1',
    delivery_time: '3-5 giorni',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: ['Fino a 5 pagine personalizzate', 'CMS per modificare contenuti', 'Blog integrato', 'SEO ottimizzato', 'Hosting Vercel 1 anno'],
    images: ['https://images.unsplash.com/photo-1547658719-da2b51169166?w=800&q=80'],
    rating: 4.8, review_count: 23, created_at: '2024-01-01',
  },
  {
    id: '4',
    name: 'Sito Ristorante con Prenotazioni',
    slug: 'sito-ristorante',
    description: 'Sito web per ristoranti con menu online, galleria e sistema prenotazioni',
    long_description: 'Sito web elegante per ristoranti, pizzerie e locali. Include menu digitale integrato, galleria piatti, sistema di prenotazione tavoli online, mappa e orari. I clienti possono prenotare direttamente dal sito.',
    price: 35,
    original_price: 69,
    category_id: '1',
    delivery_time: '2-4 giorni',
    is_customizable: true,
    is_bestseller: true,
    is_digital: true,
    badge: 'bestseller',
    includes: ['Menu digitale integrato', 'Sistema prenotazioni tavoli', 'Galleria piatti', 'Mappa e orari apertura', 'Form contatto e WhatsApp'],
    images: ['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80'],
    rating: 4.9, review_count: 38, created_at: '2024-01-01',
  },
  {
    id: '5',
    name: 'Sito Parrucchiere / Salone',
    slug: 'sito-parrucchiere',
    description: 'Sito elegante per parrucchieri, centri estetici e saloni di bellezza',
    long_description: 'Sito web professionale per saloni di bellezza, parrucchieri e centri estetici. Include galleria lavori, listino prezzi, sistema prenotazione online, sezione team e recensioni clienti.',
    price: 29,
    original_price: 55,
    category_id: '1',
    delivery_time: '24-48 ore',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: '24h',
    includes: ['Galleria lavori e foto', 'Listino prezzi', 'Prenotazione online', 'Sezione team', 'Recensioni clienti'],
    images: ['https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80'],
    rating: 4.7, review_count: 19, created_at: '2024-01-01',
  },
  {
    id: '6',
    name: 'Sito Freelancer / Consulente',
    slug: 'sito-freelancer',
    description: 'Sito personale per consulenti, coach, professionisti e liberi professionisti',
    long_description: 'Sito web personale per affermarti come professionista nel tuo settore. Include bio, servizi offerti, casi studio, testimonianze clienti, blog e form di contatto. Design pulito e autorevole.',
    price: 22,
    original_price: 45,
    category_id: '1',
    delivery_time: '24-48 ore',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: ['Bio e presentazione', 'Sezione servizi', 'Casi studio', 'Testimonianze clienti', 'Form contatto premium'],
    images: ['https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&q=80'],
    rating: 4.7, review_count: 14, created_at: '2024-01-01',
  },
  {
    id: '7',
    name: 'E-commerce Prodotti Digitali',
    slug: 'ecommerce-digitale',
    description: 'Negozio online completo per vendere prodotti digitali, corsi o abbonamenti',
    long_description: 'Piattaforma e-commerce ottimizzata per la vendita di prodotti digitali: ebook, corsi, template, software. Include carrello, pagamenti Stripe/PayPal, download automatico dopo l\'acquisto e area clienti.',
    price: 40,
    original_price: 79,
    category_id: '1',
    delivery_time: '4-6 giorni',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: ['Catalogo prodotti illimitato', 'Pagamenti Stripe + PayPal', 'Download automatico post-acquisto', 'Area clienti', 'Dashboard vendite'],
    images: ['https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80'],
    rating: 4.8, review_count: 11, created_at: '2024-01-01',
  },

  // ─── MENU DIGITALI ───
  {
    id: '8',
    name: 'Menu Digitale QR Ristorante',
    slug: 'menu-digitale-qr',
    description: 'Menu digitale per ristoranti con QR code, allergenici e aggiornamenti illimitati',
    long_description: 'Il menu digitale perfetto per il tuo ristorante. Accessibile via QR code, con indicatori allergenici conformi alle normative EU, prezzi aggiornabili in tempo reale, immagini dei piatti e sezioni personalizzabili.',
    price: 19,
    original_price: 39,
    category_id: '2',
    delivery_time: '24 ore',
    is_customizable: true,
    is_bestseller: true,
    is_digital: true,
    badge: '24h',
    includes: ['QR code personalizzato', 'Allergenici EU conformi', 'Aggiornamenti illimitati', 'Multilingua IT + EN', '1 anno hosting incluso'],
    images: ['https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80'],
    rating: 5.0, review_count: 89, created_at: '2024-01-01',
  },
  {
    id: '9',
    name: 'Menu Bar & Cocktail Bar',
    slug: 'menu-bar-cocktail',
    description: 'Menu digitale elegante per bar, pub e cocktail bar con QR code personalizzato',
    long_description: 'Menu digitale studiato per bar e locali notturni. Design elegante dark mode, sezioni cocktail, spirits, birre artigianali e soft drink. QR code personalizzato con logo e colori del locale.',
    price: 15,
    original_price: 29,
    category_id: '2',
    delivery_time: '24 ore',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: '24h',
    includes: ['Design dark mode elegante', 'QR code con logo', 'Sezioni cocktail e spirits', 'Aggiornamenti 1 anno', 'Filtro per categoria'],
    images: ['https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80'],
    rating: 4.8, review_count: 34, created_at: '2024-01-01',
  },
  {
    id: '10',
    name: 'Menu Pizzeria con Ingredienti',
    slug: 'menu-pizzeria',
    description: 'Menu digitale specifico per pizzerie con ingredienti, varianti e opzioni senza glutine',
    long_description: 'Menu digitale progettato appositamente per pizzerie. Mostra ingredienti di ogni pizza, varianti (calzone, bianca, rossa), opzioni senza glutine e vegane. I clienti possono filtrare per ingrediente o tipologia.',
    price: 17,
    original_price: 32,
    category_id: '2',
    delivery_time: '24 ore',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: ['Lista ingredienti per pizza', 'Filtro senza glutine / vegano', 'Prezzi con varianti', 'QR code personalizzato', 'Aggiornamenti illimitati'],
    images: ['https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80'],
    rating: 4.8, review_count: 27, created_at: '2024-01-01',
  },
  {
    id: '11',
    name: 'Menu Gelateria / Pasticceria',
    slug: 'menu-gelateria',
    description: 'Menu digitale colorato e accattivante per gelaterie, pasticcerie e caffetterie',
    long_description: 'Menu digitale pensato per gelaterie e pasticcerie. Design colorato e appetitoso, sezioni gusti gelato, torte personalizzate, brioche e bevande. Perfetto per attirare clienti e mostrare le specialità del giorno.',
    price: 14,
    original_price: 27,
    category_id: '2',
    delivery_time: '24 ore',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: '24h',
    includes: ['Design colorato e appetitoso', 'Sezione "gusti del giorno"', 'Allergenici integrati', 'QR code personalizzato', 'Aggiornamenti stagionali'],
    images: ['https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&q=80'],
    rating: 4.9, review_count: 22, created_at: '2024-01-01',
  },
  {
    id: '12',
    name: 'Menu Multilingua Turistico',
    slug: 'menu-multilingua',
    description: 'Menu digitale in 4 lingue per ristoranti e locali in zone turistiche',
    long_description: 'Menu digitale con supporto multilingua completo: italiano, inglese, tedesco e francese. Ideale per ristoranti e locali in zone turistiche, aeroporti o hotel. Il cliente seleziona la lingua dal QR code.',
    price: 22,
    original_price: 42,
    category_id: '2',
    delivery_time: '48 ore',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: ['4 lingue: IT, EN, DE, FR', 'Selezione lingua automatica', 'Allergenici in tutte le lingue', 'QR code unico per tutte le lingue', 'Aggiornamenti illimitati'],
    images: ['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80'],
    rating: 4.9, review_count: 18, created_at: '2024-01-01',
  },
  {
    id: '13',
    name: 'Menu Digitale + Ordini al Tavolo',
    slug: 'menu-ordini-tavolo',
    description: 'Menu digitale avanzato con sistema di ordinazione direttamente dal telefono',
    long_description: 'Il sistema più avanzato: i clienti scansionano il QR, scelgono i piatti e inviano l\'ordine direttamente in cucina. Zero attese, zero errori. Include pannello gestione ordini per il personale.',
    price: 35,
    original_price: 65,
    category_id: '2',
    delivery_time: '3-5 giorni',
    is_customizable: true,
    is_bestseller: true,
    is_digital: true,
    badge: 'bestseller',
    includes: ['Ordini direttamente dal telefono', 'Notifiche in cucina in tempo reale', 'Pannello gestione ordini', 'Storico ordini per tavolo', 'QR code per ogni tavolo'],
    images: ['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80'],
    rating: 4.9, review_count: 41, created_at: '2024-01-01',
  },

  // ─── FOGLI EXCEL ───
  {
    id: '14',
    name: 'Gestionale Inventario Magazzino',
    slug: 'gestionale-inventario-excel',
    description: 'Foglio Excel professionale per gestione inventario e magazzino',
    long_description: 'Template Excel avanzato per gestire il tuo magazzino in modo professionale. Include tracciamento scorte, alert automatici, report grafici, gestione fornitori e storico movimenti.',
    price: 10,
    original_price: 19,
    category_id: '3',
    delivery_time: '1 ora',
    is_customizable: false,
    is_bestseller: true,
    is_digital: true,
    badge: '24h',
    includes: ['Dashboard scorte in tempo reale', 'Alert livello minimo automatico', 'Report mensili grafici', 'Gestione fornitori', 'Storico movimenti'],
    images: ['https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80'],
    rating: 4.7, review_count: 134, created_at: '2024-01-01',
  },
  {
    id: '15',
    name: 'Fatturazione Automatica',
    slug: 'fatturazione-automatica-excel',
    description: 'Genera fatture professionali in automatico con calcolo IVA e archivio clienti',
    long_description: 'Genera fatture professionali in pochi secondi. Inserisci i dati cliente e i servizi, il foglio calcola automaticamente IVA, totali, numerazione progressiva e archivia tutto.',
    price: 12,
    original_price: 24,
    category_id: '3',
    delivery_time: '1 ora',
    is_customizable: false,
    is_bestseller: false,
    is_digital: true,
    badge: '24h',
    includes: ['Generazione fatture automatica', 'Calcolo IVA automatico', 'Archivio clienti', 'Numerazione progressiva', 'Export PDF integrato'],
    images: ['https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80'],
    rating: 4.8, review_count: 67, created_at: '2024-01-01',
  },
  {
    id: '16',
    name: 'Budget e Contabilità Personale',
    slug: 'budget-contabilita-personale',
    description: 'Tieni traccia delle tue entrate, spese e risparmi con grafici automatici',
    long_description: 'Il foglio Excel definitivo per gestire le tue finanze personali. Inserisci entrate e uscite, categorizza le spese, monitora i risparmi e visualizza tutto con grafici chiari e intuitivi.',
    price: 10,
    original_price: 18,
    category_id: '3',
    delivery_time: '1 ora',
    is_customizable: false,
    is_bestseller: false,
    is_digital: true,
    badge: '24h',
    includes: ['Tracciamento entrate/uscite', 'Categorie personalizzabili', 'Grafici automatici mensili', 'Obiettivi di risparmio', 'Report annuale'],
    images: ['https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&q=80'],
    rating: 4.7, review_count: 89, created_at: '2024-01-01',
  },
  {
    id: '17',
    name: 'Gestione Dipendenti e Presenze',
    slug: 'gestione-dipendenti-presenze',
    description: 'Foglio Excel per gestire turni, presenze, ferie e straordinari del personale',
    long_description: 'Gestisci il personale in modo professionale. Tieni traccia delle presenze, calcola automaticamente le ore di straordinario, gestisci richieste ferie e genera report mensili per la busta paga.',
    price: 15,
    original_price: 28,
    category_id: '3',
    delivery_time: '1 ora',
    is_customizable: false,
    is_bestseller: false,
    is_digital: true,
    badge: '24h',
    includes: ['Foglio presenze mensile', 'Calcolo automatico straordinari', 'Gestione ferie e permessi', 'Report per la busta paga', 'Calendario turni'],
    images: ['https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80'],
    rating: 4.6, review_count: 43, created_at: '2024-01-01',
  },
  {
    id: '18',
    name: 'CRM Clienti e Vendite',
    slug: 'crm-clienti-vendite',
    description: 'Gestisci clienti, trattative e pipeline di vendita con questo CRM Excel',
    long_description: 'Un CRM completo in Excel per piccole imprese. Archivio clienti con storico contatti, pipeline vendite con fasi trattativa, promemoria follow-up automatici e report sulle performance commerciali.',
    price: 18,
    original_price: 35,
    category_id: '3',
    delivery_time: '1 ora',
    is_customizable: false,
    is_bestseller: true,
    is_digital: true,
    badge: 'bestseller',
    includes: ['Archivio clienti completo', 'Pipeline vendite visuale', 'Promemoria follow-up', 'Report performance commerciali', 'Storico comunicazioni'],
    images: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80'],
    rating: 4.8, review_count: 56, created_at: '2024-01-01',
  },
  {
    id: '19',
    name: 'Pianificazione Progetto e Gantt',
    slug: 'pianificazione-progetto-gantt',
    description: 'Template Excel con diagramma di Gantt per pianificare e monitorare progetti',
    long_description: 'Pianifica i tuoi progetti in modo professionale con un diagramma di Gantt interattivo. Assegna task, scadenze e risorse. Il foglio calcola automaticamente la percentuale di completamento e i ritardi.',
    price: 14,
    original_price: 27,
    category_id: '3',
    delivery_time: '1 ora',
    is_customizable: false,
    is_bestseller: false,
    is_digital: true,
    badge: '24h',
    includes: ['Diagramma di Gantt interattivo', 'Assegnazione task e risorse', 'Calcolo % completamento', 'Alert scadenze', 'Report stato progetto'],
    images: ['https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80'],
    rating: 4.7, review_count: 38, created_at: '2024-01-01',
  },
  {
    id: '20',
    name: 'Listino Prezzi e Preventivi',
    slug: 'listino-prezzi-preventivi',
    description: 'Crea preventivi professionali in secondi con calcolo automatico di sconti e margini',
    long_description: 'Genera preventivi professionali in pochi secondi. Inserisci prodotti o servizi dal listino prezzi, applica sconti, il foglio calcola automaticamente margini, totali e genera un PDF da inviare al cliente.',
    price: 12,
    original_price: 22,
    category_id: '3',
    delivery_time: '1 ora',
    is_customizable: false,
    is_bestseller: false,
    is_digital: true,
    badge: '24h',
    includes: ['Listino prezzi aggiornabile', 'Calcolo sconti automatico', 'Calcolo margini', 'Generazione preventivo PDF', 'Archivio preventivi inviati'],
    images: ['https://images.unsplash.com/photo-1568952433726-3896e3881c65?w=800&q=80'],
    rating: 4.7, review_count: 29, created_at: '2024-01-01',
  },

  // ─── AUTOMAZIONI ───
  {
    id: '21',
    name: 'Chatbot WhatsApp Business',
    slug: 'chatbot-whatsapp',
    description: 'Chatbot automatico per WhatsApp Business con risposte personalizzate 24/7',
    long_description: 'Automatizza il tuo supporto clienti con un chatbot intelligente per WhatsApp Business. Risponde alle domande frequenti, prende prenotazioni e invia informazioni automaticamente anche di notte.',
    price: 35,
    original_price: 69,
    category_id: '4',
    delivery_time: '2-3 giorni',
    is_customizable: true,
    is_bestseller: true,
    is_digital: true,
    badge: 'bestseller',
    includes: ['Setup WhatsApp Business API', 'Risposte automatiche 24/7', 'Gestione prenotazioni', 'Dashboard analytics', '1 mese supporto incluso'],
    images: ['https://images.unsplash.com/photo-1611262588024-d12430b98920?w=800&q=80'],
    rating: 4.9, review_count: 31, created_at: '2024-01-01',
  },
  {
    id: '22',
    name: 'Automazione Email Marketing',
    slug: 'automazione-email',
    description: 'Sequenze email automatiche per acquisire e fidelizzare clienti',
    long_description: 'Crea sequenze email automatiche per acquisire e fidelizzare clienti. Setup completo con welcome email, follow-up post acquisto, recupero carrelli abbandonati e newsletter automatiche.',
    price: 25,
    original_price: 49,
    category_id: '4',
    delivery_time: '2-3 giorni',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: ['Sequenza welcome email', 'Follow-up post acquisto', 'Newsletter automatica', 'Template email brandizzati', 'Report aperture e click'],
    images: ['https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800&q=80'],
    rating: 4.7, review_count: 19, created_at: '2024-01-01',
  },
  {
    id: '23',
    name: 'Chatbot Instagram DM',
    slug: 'chatbot-instagram-dm',
    description: 'Rispondi automaticamente ai messaggi diretti Instagram con un bot intelligente',
    long_description: 'Non perdere più nessun cliente su Instagram. Il bot risponde automaticamente ai DM, qualifica i lead, invia il listino prezzi, prenota appuntamenti e instrada le richieste urgenti a te.',
    price: 28,
    original_price: 55,
    category_id: '4',
    delivery_time: '2-3 giorni',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: ['Risposte automatiche DM', 'Qualificazione lead', 'Invio listino automatico', 'Prenotazione appuntamenti', 'Notifiche urgenti su WhatsApp'],
    images: ['https://images.unsplash.com/photo-1611262588024-d12430b98920?w=800&q=80'],
    rating: 4.8, review_count: 22, created_at: '2024-01-01',
  },
  {
    id: '24',
    name: 'Integrazione Google Sheets + Notifiche',
    slug: 'integrazione-google-sheets',
    description: 'Automatizza la raccolta dati da form, email o CRM verso Google Sheets con notifiche',
    long_description: 'Collega i tuoi strumenti a Google Sheets automaticamente. Ogni nuovo contatto dal sito, ogni ordine, ogni email viene salvato nel foglio e ti arriva una notifica su WhatsApp o Telegram in tempo reale.',
    price: 20,
    original_price: 38,
    category_id: '4',
    delivery_time: '24-48 ore',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: '24h',
    includes: ['Connessione form → Google Sheets', 'Notifiche WhatsApp / Telegram', 'Filtri e regole personalizzate', 'Dashboard dati automatica', 'Setup Make / Zapier'],
    images: ['https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80'],
    rating: 4.7, review_count: 16, created_at: '2024-01-01',
  },
  {
    id: '25',
    name: 'Bot Prenotazioni Automatiche',
    slug: 'bot-prenotazioni-automatiche',
    description: 'Sistema automatico per gestire prenotazioni via WhatsApp, Instagram o sito web',
    long_description: 'Automatizza completamente le prenotazioni del tuo business. I clienti scelgono giorno e ora, ricevono conferma automatica, reminder 24 ore prima e il tutto viene sincronizzato con Google Calendar.',
    price: 32,
    original_price: 62,
    category_id: '4',
    delivery_time: '3-4 giorni',
    is_customizable: true,
    is_bestseller: true,
    is_digital: true,
    badge: 'bestseller',
    includes: ['Prenotazioni via WhatsApp/sito', 'Conferme automatiche', 'Reminder 24h prima', 'Sync Google Calendar', 'Gestione cancellazioni'],
    images: ['https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80'],
    rating: 4.9, review_count: 44, created_at: '2024-01-01',
  },
  {
    id: '26',
    name: 'Automazione Post Social Media',
    slug: 'automazione-social-media',
    description: 'Pianifica e pubblica automaticamente post su Instagram, Facebook e LinkedIn',
    long_description: 'Dimentica di postare manualmente ogni giorno. Pianifica un mese di contenuti in anticipo, il sistema pubblica automaticamente nei giorni e orari migliori su tutti i tuoi canali social.',
    price: 22,
    original_price: 42,
    category_id: '4',
    delivery_time: '2-3 giorni',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: ['Pubblicazione automatica IG/FB/LI', 'Calendario editoriale', 'Orari ottimali automatici', 'Report engagement', 'Setup Buffer / Hootsuite'],
    images: ['https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&q=80'],
    rating: 4.6, review_count: 28, created_at: '2024-01-01',
  },

  // ─── APP MOBILE ───
  {
    id: '27',
    name: 'App PWA Business',
    slug: 'app-pwa-business',
    description: 'Progressive Web App installabile su iOS e Android per il tuo business',
    long_description: 'Una PWA professionale che funziona come una vera app su qualsiasi dispositivo. Installabile dalla home, funziona offline, push notification e performance ottimizzate.',
    price: 40,
    original_price: 79,
    category_id: '5',
    delivery_time: '5-7 giorni',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: ['Installabile iOS + Android', 'Funzionamento offline', 'Push notification', 'Performance ottimizzate', '3 mesi supporto'],
    images: ['https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80'],
    rating: 4.8, review_count: 12, created_at: '2024-01-01',
  },
  {
    id: '28',
    name: 'App Prenotazioni Mobile',
    slug: 'app-prenotazioni',
    description: 'App mobile per gestire prenotazioni e appuntamenti del tuo locale',
    long_description: 'App PWA per gestire prenotazioni in modo professionale. I clienti prenotano online, ricevono conferma automatica e reminder. Tu gestisci tutto da una dashboard intuitiva.',
    price: 35,
    original_price: 69,
    category_id: '5',
    delivery_time: '5-7 giorni',
    is_customizable: true,
    is_bestseller: true,
    is_digital: true,
    badge: 'bestseller',
    includes: ['Booking online clienti', 'Conferme automatiche', 'Reminder SMS/email', 'Dashboard gestione', 'Calendario integrato'],
    images: ['https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80'],
    rating: 4.9, review_count: 28, created_at: '2024-01-01',
  },
  {
    id: '29',
    name: 'App Catalogo Prodotti',
    slug: 'app-catalogo-prodotti',
    description: 'App mobile per mostrare il tuo catalogo prodotti con prezzi e ordini',
    long_description: 'App PWA che trasforma il tuo catalogo in un\'esperienza mobile premium. I clienti sfogliano i prodotti, vedono prezzi e disponibilità in tempo reale, e possono contattarti direttamente per ordinare.',
    price: 30,
    original_price: 59,
    category_id: '5',
    delivery_time: '5-7 giorni',
    is_customizable: true,
    is_bestseller: false,
    is_digital: true,
    badge: 'customizable',
    includes: ['Catalogo prodotti dinamico', 'Ricerca e filtri avanzati', 'Prezzi in tempo reale', 'Contatto diretto WhatsApp', 'Installabile su telefono'],
    images: ['https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80'],
    rating: 4.7, review_count: 9, created_at: '2024-01-01',
  },
]
